<a href="https://colab.research.google.com/github/svyatoslavn1000/data_science_np_pd/blob/main/lesson_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Часть 1

In [2]:
import numpy as np

In [26]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [27]:
mean_a =  a.mean(axis = 0)
mean_a.T 


array([2. , 8.4])

In [38]:
a_centered =  a- mean_a
a_centered
a_centered[0:, 0]
a_centered[0:, 1]

array([-1.,  0.,  1.,  1., -1.])

In [41]:
p = a_centered[0:, 0]
q = a_centered[0:, 1]
a_centered_sp = p @ q
a_centered_sp

8.0

In [43]:
covar = a_centered_sp/(p.size - 1)

In [50]:
if(covar == np.cov(a.transpose())[0,1]):
  print('Ok')
else:
  print('WARNING!!!')

Ok


##Часть 2

###Задание 1

In [51]:
import pandas as pd

In [54]:
authors = pd.DataFrame({"author_id" : [1, 2, 3], "author_name" : ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [60]:
books = pd.DataFrame({"author_id": [1, 1, 1, 2, 2, 3, 3], "book_title" : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
        "price" : [450, 300, 350, 500, 450, 370, 290] })
books            

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

###Задание 2

In [84]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

###Задание 3

In [63]:
 top5 = authors_price.nlargest(5, ['price'])
 top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

###Задание 4

In [79]:
groupby = authors_price.groupby("author_name")
authors_stat = groupby.agg({"price" : [ "min", "max", "mean"]})
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

###Задание 5**

In [93]:
cover = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price["cover"] = cover
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [81]:
import numpy as np

In [94]:
book_info = pd.pivot_table(authors_price, values = "author_id", index = ['author_name'], columns = ['cover'], aggfunc =  np.unique, fill_value = 0)

In [95]:
book_info

cover        мягкая  твердая
author_name                 
Островский        3        0
Тургенев          1        1
Чехов             0        2

In [96]:
book_info.to_pickle('book_info.pkl')

In [97]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский        3        0
Тургенев          1        1
Чехов             0        2